import { app } from '../app'
import { PackageVersion } from '../ncu'
import { PullRequestBodyCreator } from './PullRequestBodyCreator'

describe('PullRequestBodyCreator', () => {
  describe('create', () => {
    it('returns pull request body', () => {
      const pullRequestBodyCreator = new PullRequestBodyCreator()
      const actual = pullRequestBodyCreator.create({
        name: '@typescript-eslint/eslint-plugin',
        currentVersion: PackageVersion.of('1.0.0'),
        newVersion: PackageVersion.of('2.0.0'),
        type: 'major'
      })
      expect(actual).toBe(`This PR updates these packages:

|package|type|current version|new version|
|---|---|---|---|
|[@typescript-eslint/eslint-plugin](https://www.npmjs.com/package/@typescript-eslint/eslint-plugin)|major|\`1.0.0\`|\`2.0.0\`|

---
This PR has been generated by [${app.name}](${app.web}) v${app.version}`)
    })
  })
})
