import { app } from '../../../app'
import type { OutdatedPackage } from '../../../core'
import { toJSON } from '../../../json'
import { createPullRequestMetadata } from '../metadata'

export const createPullRequestBody = (outdatedPackage: OutdatedPackage): string => {
  const appName = app.name
  const appVersion = app.version
  const appWeb = app.web
  const currentVersion = outdatedPackage.currentVersion.version
  const newVersion = outdatedPackage.newVersion.version
  const packageName = outdatedPackage.name
  const level = outdatedPackage.level
  const metadata = toJSON(createPullRequestMetadata([outdatedPackage]), { pretty: true })
  // TODO: rename type to level
  return `This PR updates these packages:

|package|type|current version|new version|
|---|---|---|---|
|[${packageName}](https://www.npmjs.com/package/${packageName})|${level}|\`${currentVersion}\`|\`${newVersion}\`|

<details>
<summary>Metadata</summary>

**Don't remove or edit this section because it will be used by npm-update-package.**

<div id="npm-update-package-metadata">

\`\`\`json
${metadata}
\`\`\`

</div>
</details>

---
This PR has been generated by [${appName}](${appWeb}) v${appVersion}`
}
