
import pkg from '../../../../package.json'
import { SemVer } from '../../../semver'
import { createPullRequestBody } from './createPullRequestBody'

describe('createPullRequestBody', () => {
  it('returns pull request body', () => {
    const actual = createPullRequestBody({
      name: '@npm-update-package/example',
      currentVersion: SemVer.of('1.0.0'),
      newVersion: SemVer.of('2.0.0'),
      level: 'major'
    })
    expect(actual).toBe(`This PR updates these packages:

|Package|Level|Current version|New version|
|---|---|---|---|
|[@npm-update-package/example](https://www.npmjs.com/package/@npm-update-package/example)|major|\`1.0.0\`|\`2.0.0\`|

<details>
<summary>Metadata</summary>

**Don't remove or edit this section because it will be used by npm-update-package.**

<div id="npm-update-package-metadata">

\`\`\`json
{
  "version": "${pkg.version}",
  "packages": [
    {
      "name": "@npm-update-package/example",
      "currentVersion": "1.0.0",
      "newVersion": "2.0.0",
      "level": "major"
    }
  ]
}
\`\`\`

</div>
</details>

---
This PR has been generated by [${pkg.name}](${pkg.homepage}) v${pkg.version}`)
  })
})
