import { createRequirePackageJSON } from '../../../util/createRequirePackageJSON.js'

const requirePackageJSON = createRequirePackageJSON(import.meta.url)
const pkg = requirePackageJSON('../../../../package.json')

export const createFooter = (): string => {
  return `This PR has been generated by [${pkg.name}](${pkg.homepage}) v${pkg.version}`
}
