import assert from 'node:assert'
import {
  describe,
  it
} from 'node:test'
import { createRequirePackageJSON } from '../../../util/createRequirePackageJSON.js'
import { createFooter } from './createFooter.js'

const pkg = createRequirePackageJSON(import.meta.url)('../../../../package.json')

await describe('createFooter', async () => {
  await it('returns footer', () => {
    const actual = createFooter()

    assert.strictEqual(actual, `This PR has been generated by [${pkg.name}](${pkg.homepage}) v${pkg.version}`)
  })
})
