import assert from 'node:assert'
import {
  describe,
  it
} from 'node:test'
import { createFooter } from './createFooter.js'
const { default: pkg } = await import('../../../../package.json')

await describe('createFooter', async () => {
  await it('returns footer', () => {
    const actual = createFooter()

    assert.strictEqual(actual, `This PR has been generated by [${pkg.name}](${pkg.homepage}) v${pkg.version}`)
  })
})
