import { createRequirePackageJSON } from '../../../util/createRequirePackageJSON.js'

const pkg = createRequirePackageJSON(import.meta.url)('../../../../package.json')

export const createFooter = (): string => {
  return `This PR has been generated by [${pkg.name}](${pkg.homepage}) v${pkg.version}`
}
