import assert from 'node:assert'
import {
  describe,
  it
} from 'node:test'
import * as app from '../../../../src/app.js'
import { createFooter } from './createFooter.js'

await describe('createFooter', async () => {
  await it('returns footer', () => {
    const actual = createFooter()

    assert.strictEqual(actual, `This PR has been generated by [${app.name}](${app.homepage}) v${app.version}`)
  })
})
