const { default: pkg } = await import('../../../../package.json')

export const createFooter = (): string => {
  return `This PR has been generated by [${pkg.name}](${pkg.homepage}) v${pkg.version}`
}
